export { Header } from './Header'
export { Footer } from './Footer'
export { HeroSection } from './HeroSection'
export { CategoriesSection } from './CategoriesSection'
export type { Category } from './CategoriesSection'
export { CourseCard } from './CourseCard'
export type { Course } from './CourseCard'
export { CourseListSection } from './CourseListSection'
export { InstructorCTA } from './InstructorEnquire'
export type { Instructor } from './InstructorEnquire'
export { Rating } from './Rating'
export { Timeline } from './TimeLine'
